import test from 'node:test';
import assert from 'node:assert/strict';
import {init} from '../src/embeds/email-statement.js';
function fixture({reduced=false,failObserver=false,failAnimation=false}={}){
 const keys=['window','document','matchMedia','getComputedStyle','IntersectionObserver','setTimeout','clearTimeout'];
 const saved=keys.map(k=>[k,globalThis[k]]),timers=new Map(),events=new Map(),docEvents=new Map(),observers=[],pulses=[];let next=0;
 const svgNodes=[];
 const node=()=>({textContent:'Email sent',append(...nodes){this.childNodes.push(...nodes)},remove(){this.removed=true},animate(frames,options){if(failAnimation)throw Error('animation unavailable');const p={frames,options,cancel(){this.cancelled=true}};pulses.push(p);return p},nodeType:1,childNodes:[],dataset:{},style:{setProperty(){}},attrs:new Map(),classes:new Set(),setAttribute(k,v){this.attrs.set(k,v)},removeAttribute(k){this.attrs.delete(k)},matches(s){return s==='[data-es-reveal]'},classList:{}});
 const rows=Array.from({length:8},()=>node());rows.forEach(n=>n.classList={add:c=>n.classes.add(c),remove:c=>n.classes.delete(c)});
 const check=node();
 const root=node();root.childNodes=rows;root.matches=s=>s==='[data-email-statement]';root.querySelectorAll=s=>s==='[data-es-reveal]'?rows:s==='.es-attachment'?rows.slice(6):s==='.es-label'?[rows[0]]:s==='.es-card'?[rows[1]]:s==='.es-check'?[rows[2]]:s==='.es-success'?[rows[3]]:s==='.es-attachments'?[rows[4]]:s==='.es-attachments-title'?[rows[5]]:[];root.querySelector=s=>s==='.es-success'?rows[3]:check;root.offsetWidth=540;
 const values={'--motion-ease-primary':'cubic-bezier(.11, .61, .27, .99)','--motion-duration-default':'770ms','--reveal-stagger-default':'200ms','--reveal-opacity-ratio':'.34'};
 globalThis.getComputedStyle=()=>({getPropertyValue:k=>values[k]||'',animationDuration:'0.462s'});
 globalThis.setTimeout=(fn,delay)=>{timers.set(++next,{fn,delay});return next};globalThis.clearTimeout=id=>timers.delete(id);
 globalThis.window={getComputedStyle:globalThis.getComputedStyle,setTimeout:globalThis.setTimeout,clearTimeout:globalThis.clearTimeout};
 globalThis.document={createElementNS(ns,tag){const n=node();n.tag=tag;svgNodes.push(n);return n},hidden:false,documentElement:{},addEventListener:(k,fn)=>docEvents.set(k,fn),removeEventListener:k=>docEvents.delete(k)};
 const media={matches:reduced,addEventListener:(k,fn)=>events.set(k,fn),removeEventListener:k=>events.delete(k)};globalThis.matchMedia=()=>media;
 globalThis.IntersectionObserver=class{constructor(fn){if(failObserver)throw Error('observer unavailable');this.fn=fn;observers.push(this)}observe(){}disconnect(){this.disconnected=true}};
 return{root,rows,svgNodes,timers,observers,events,docEvents,media,pulses,values,visible(v=true){observers[0].fn([{isIntersecting:v,intersectionRatio:typeof v==='number'?v:v?1:0}])},flush(){const ts=[...timers].sort((a,b)=>a[1].delay-b[1].delay);for(const [id,{fn}]of ts){timers.delete(id);fn()}},restore(){for(const[k,v]of saved)v===undefined?delete globalThis[k]:globalThis[k]=v}};
}
test('three equal dots, no path end-cap dots, and a cancellable animated loop',()=>{const f=fixture();try{const dispose=init(f.root);init(f.root);assert.equal(f.observers.length,1);f.visible();assert.ok(f.root.attrs.has('data-es-ready'));assert.deepEqual([...f.timers.values()].slice(0,8).map(t=>t.delay),[400,1170,1940,2140,2340,2540,2740,2940]);assert.equal(f.rows[3].textContent,'Email sending');const dots=f.svgNodes.filter(n=>n.tag==='circle'),paths=f.svgNodes.filter(n=>n.tag==='path');assert.equal(dots.length,3);assert.deepEqual(dots.map(n=>n.attrs.get('cx')),['12','20','28']);assert.deepEqual(paths.map(n=>n.style.opacity),['0','0']);const firstCycle=f.pulses.length;f.flush();assert.ok(f.pulses.length>firstCycle);assert.equal(f.svgNodes.filter(n=>n.tag==='circle').length,3);assert.equal(f.pulses[0].cancelled,true);assert.ok(f.timers.size>0);dispose();assert.equal(f.rows[3].textContent,'Email sent');assert.equal(f.timers.size,0);assert.equal(f.docEvents.size,0);assert.equal(f.root.attrs.has('data-es-ready'),false);const again=init(f.root);assert.equal(f.observers.length,2);again()}finally{f.restore()}});

for(const condition of ['offscreen','hidden','reduced'])test(`${condition} cancels pending entrance and keeps the static graphic visible`,()=>{const f=fixture();try{const dispose=init(f.root);f.visible();if(condition==='offscreen')f.visible(false);if(condition==='hidden'){document.hidden=true;f.docEvents.get('visibilitychange')()}if(condition==='reduced'){f.media.matches=true;f.events.get('change')()}assert.equal(f.timers.size,0);assert.equal(f.root.attrs.has('data-es-ready'),condition==='offscreen');assert.equal(f.rows[3].textContent,'Email sent');dispose()}finally{f.restore()}});
test('initial reduced motion and observer failure never hide the fallback',()=>{for(const options of [{reduced:true},{failObserver:true}]){const f=fixture(options);try{const d=init(f.root);if(!options.failObserver)f.visible();assert.equal(f.root.attrs.has('data-es-ready'),false);assert.equal(f.timers.size,0);d()}finally{f.restore()}}});

test('failed sending setup leaves the fully revealed static fallback',()=>{const f=fixture({failAnimation:true});try{const d=init(f.root);f.visible();assert.doesNotThrow(()=>f.flush());assert.equal(f.root.attrs.has('data-es-ready'),false);assert.equal(f.timers.size,0);d()}finally{f.restore()}});

test('waits for 70 percent and rearms after fully leaving the viewport',()=>{const f=fixture();try{const d=init(f.root);assert.ok(f.root.attrs.has('data-es-ready'));f.visible(.69);assert.equal(f.timers.size,0);f.visible(.7);assert.equal(f.timers.size,12);f.flush();f.visible(false);assert.ok(f.root.attrs.has('data-es-ready'));f.visible(.7);assert.equal(f.timers.size,12);d()}finally{f.restore()}});
